import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LandingPage from '@/components/LandingPage';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PantryPulse",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const isLandingPage = typeof window !== 'undefined' && window.location.pathname === '/';

  return (
    <html lang="en">
      <body>
        {isLandingPage ? <LandingPage /> : children}
      </body>
    </html>
  );
}
